# This is a config for E2B sandbox template.
# You can use template ID (aojmf8i9vgzlaly2aaoh) or template name (vibenextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibenextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibenextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibenextjs-test-2')

team_id = "8cbb7263-da5b-455f-878d-834560a246fd"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibenextjs-test-2"
template_id = "aojmf8i9vgzlaly2aaoh"
